import { Injectable } from '@angular/core';
import { BehaviorSubject } from 'rxjs';
import { InterventionComponent } from '../intervention-component/intervention-component';

type Lang = 'fr' | 'en';

@Injectable({
  providedIn: 'root'
})
export class LangService {
  private langSubject = new BehaviorSubject<Lang>('fr');
  lang$ = this.langSubject.asObservable();

  private translations = {
    fr: {
      // Commun
      id: 'ID',
      name: 'Nom',
      actions: 'Actions',
      add: 'Ajouter',
      edit: 'Modifier',
      save: 'Enregistrer',
      delete: 'Supprimer',
      confirm: 'Confirmer',
      cancel: 'Annuler',
      emptyField: 'Le champ est vide !',
      ok: 'OK',
      page: 'Page',
      of: 'sur',
      quantity: 'Quantité',
      stock: 'stock',

      // Messages
      confirmDeleteGeneric: 'Voulez-vous vraiment supprimer cet élément ?',
      actionUndone: 'Cette action ne peut pas être annulée.',
      noResults: 'Aucun résultat trouvé',

      // Notifications de succès
      successAdd: 'Ajout avec succès !',
      successEdit: 'Modification avec succès !',
      successDelete: 'Suppression avec succès !',

      // Compagnies
      companyTitle: 'Liste Campagny',
      companySubtitle: 'Liste de toutes les companies',
      addCompany: 'Nouvelle compagnie',
      searchCompany: ' Rechercher une entreprise...',
      noCompanies: 'Aucune compagnie trouvée',
      companyName: 'Nom de l\'entreprise',
      enterCompanyName: 'Entrez le nom de l\'entreprise',
      companyExists: 'L\'entreprise existe déjà !',
      companyEmptyField: 'Le nom de l\'entreprise ne peut pas être vide !',
      confirmDeleteCompany: 'Voulez-vous vraiment supprimer cette entreprise ?',
      companyAdded: 'Entreprise ajoutée avec succès !',
      companyUpdated: 'Entreprise mise à jour avec succès !',
      companyDeleted: 'Entreprise supprimée avec succès !',
      
      // Problèmes
      problemTitle: 'Problèmes',
      problemSubtitle: 'Liste de tous les problèmes',
      addProblem: 'Nouveau problème',
      searchProblem: '🔍 Rechercher un problème...',
      noProblems: 'Aucun problème trouvé',
      problemName: 'Nom du problème',
      enterProblemName: 'Entrez le nom du problème',
      problemExists: 'Un problème avec ce nom existe déjà !',
      problemEmptyField: 'Le nom du problème ne peut pas être vide !',
      confirmDeleteProblem: 'Voulez-vous vraiment supprimer ce problème ?',
      problemAdded: 'Problème ajouté avec succès !',
      problemUpdated: 'Problème mis à jour avec succès !',
      problemDeleted: 'Problème supprimé avec succès !',

      // Solutions
      solutionTitle: 'Solutions',
      solutionSubtitle: 'Liste de toutes les solutions',
      addSolution: 'Nouvelle solution',
      searchSolution: ' Rechercher une solution...',
      noSolutions: 'Aucune solution trouvée',
      solutionName: 'Nom de la solution',
      enterSolutionName: 'Entrez le nom de la solution',
      solutionExists: 'Une solution avec ce nom existe déjà !',
      solutionEmptyField: 'Le nom de la solution ne peut pas être vide !',
      confirmDeleteSolution: 'Voulez-vous vraiment supprimer cette solution ?',
      solutionAdded: 'Solution ajoutée avec succès !',
      solutionUpdated: 'Solution mise à jour avec succès !',
      solutionDeleted: 'Solution supprimée avec succès !',

      zoneTitle: 'Zones',
      zoneSubtitle: 'Liste de toutes les zones',
      addZone: 'Nouvelle zone',
      searchZone: ' Rechercher une zone...',
      noZones: 'Aucune zone trouvée',
      zoneName: 'Nom de la zone',
      enterZoneName: 'Entrez le nom de la zone',
      zoneExists: 'Une zone avec ce nom existe déjà !',
      zoneEmptyField: 'Le nom de la zone ne peut pas être vide !',
      confirmDeleteZone: 'Voulez-vous vraiment supprimer cette zone ?',
      zoneAdded: 'Zone ajoutée avec succès !',
      zoneUpdated: 'Zone mise à jour avec succès !',
      zoneDeleted: 'Zone supprimée avec succès !',
      cannotDelete: 'Suppression impossible',
      zoneHasCounters: 'Cette zone contient des comptoirs et ne peut pas être supprimée.',
      deleteCountersFirst: 'Veuillez d\'abord supprimer tous les comptoirs associés à cette zone.',

      counterTitle: 'Comptoires',
      counterSubtitle: 'Liste de tous les comptoires',
      addCounter: 'Nouveau comptoire',
      searchCounter: ' Rechercher un comptoire...',
      noCounters: 'Aucun comptoire trouvé',
      counterName: 'Nom du comptoire',
      enterCounterName: 'Entrez le nom du comptoire',
      selectZone: 'Sélectionnez une zone',
      zone: 'Zone',
      zoneRequired: 'Zone nécessaire',
      counterNeedsZone: 'Veuillez sélectionner une zone pour ce comptoir.',
      zoneUnavailable: 'Zone indisponible',
      counterExists: 'Un comptoire avec ce nom existe déjà !',
      counterEmptyField: 'Le nom du comptoire ne peut pas être vide !',
      confirmDeleteCounter: 'Voulez-vous vraiment supprimer ce comptoire ?',
      counterAdded: 'Comptoire ajouté avec succès !',
      counterUpdated: 'Comptoire mis à jour avec succès !',
      counterDeleted: 'Comptoire supprimé avec succès !',
      
      // Équipements
      equipementTitle: 'Équipements',
      equipementSubtitle: 'Liste de tous les équipements',
      addEquipement: 'Nouvel équipement',
      searchEquipement: '🔍 Rechercher un équipement...',
      noEquipements: 'Aucun équipement trouvé',
      nameEquipement: 'Nom de l\'équipement',
      enterEquipementName: 'Entrez le nom de l\'équipement',
      quantite: 'Quantité',
      enterQuantite: 'Entrez la quantité',
      equipementExists: 'Un équipement avec ce nom existe déjà !',
      equipementEmptyField: 'Les champs ne peuvent pas être vides !',
      confirmDeleteEquipement: 'Voulez-vous vraiment supprimer cet équipement ?',
      equipementAdded: 'Équipement ajouté avec succès !',
      equipementUpdated: 'Équipement mis à jour avec succès !',
      equipementDeleted: 'Équipement supprimé avec succès !',
  // Login
  loginTitle: 'Connexion',
  loginUsername: 'Pseudonyme',
  loginPassword: 'Mot de passe',
  loginEnterUsername: 'Entrez votre identifiant',
  loginEnterPassword: 'Entrez votre mot de passe',
  loginSubmit: 'Se connecter',
  loginMissingFields: 'Veuillez remplir tous les champs',
  loginInvalid: 'Identifiants invalides',
      
      // Projets
      projectTitle: 'Projets',
      projectSubtitle: 'Gérez vos projets et leurs équipements',
      addProject: 'Nouveau projet',
      createProject: 'Créer un projet',
      projectName: 'Nom du projet',
      enterProjectName: 'Entrez le nom du projet',
      selectEquipment: 'Choisir un équipement',
      equipmentQuantity: 'Quantité',
      selectedEquipments: 'Équipements sélectionnés',
      projectListTitle: 'Liste des projets',
      noProjects: 'Aucun projet trouvé',
      modifyProject: 'Modifier projet',
      saveProject: 'Enregistrer le projet',
      deleteProjectConfirm: 'Voulez-vous vraiment supprimer ce projet ?',
      projectAdded: 'Projet ajouté avec succès !',
      projectUpdated: 'Projet mis à jour avec succès !',
      projectDeleted: 'Projet supprimé avec succès !',
      equipments: 'Équipements',
      addEquipment: 'Ajouter équipment',
      equipment: 'Équipement',
      unknownEquipment: 'Équipement inconnu',
      editEquipment: 'Modifier',
      deleteEquipment: 'Supprimer',
      chooseEquipment: 'Choisir un équipement',
      equipmentStock: 'stock',
      removeEquipment: 'X',

      // Techniciens
      firstname: 'Prénom',
      enterFirstname: 'Entrez le prénom',
      lastname: 'Nom',
      enterLastname: 'Entrez le nom',
      pseudoname: 'Surnom',
      enterPseudoname: 'Entrez le surnom',
      role: 'Rôle',
      enterRole: 'Entrez le rôle',
      motDePass: 'Mot de passe',
      enterMotDePass: 'Entrez le mot de passe',
      aeroport: 'Aéroport',
      enterAeroport: 'Choisissez l\'aéroport',
      technicienTitle: 'Techniciens', 
      technicienSubtitle: 'Liste de tous les techniciens',
      addTechnicien: 'Nouveau technicien',
      searchTechnicien: ' Rechercher un technicien...',
      noTechniciens: 'Aucun technicien trouvé',
      technicienName: 'Nom du technicien',  
      enterTechnicienName: 'Entrez le nom du technicien',
      technicienExists: 'Un technicien avec ce nom existe déjà !',
      technicienEmptyField: 'Veuillez remplir tous les champs !',
      confirmDeleteTechnicien: 'Voulez-vous vraiment supprimer ce technicien ?',
      technicienAdded: 'Technicien ajouté avec succès !',
      technicienUpdated: 'Technicien mis à jour avec succès !',
      technicienDeleted: 'Technicien supprimé avec succès !',

      // Aeroports
      aeroportTitle: 'Liste des Aéroports',
      aeroportSubtitle: 'Liste de tous les aéroports',
      addAeroport: 'Nouvel aéroport',
      searchAeroport: '🔍 Rechercher un aéroport...',
      noAeroports: 'Aucun aéroport trouvé',
      aeroportName: 'Nom de l\'aéroport',
      enterAeroportName: 'Entrez le nom de l\'aéroport',
      aeroportExists: 'Un aéroport avec ce nom existe déjà !',
      aeroportEmptyField: 'Le nom de l\'aéroport ne peut pas être vide !',
      confirmDeleteAeroport: 'Voulez-vous vraiment supprimer cet aéroport ?',
      aeroportAdded: 'Aéroport ajouté avec succès !',
      aeroportUpdated: 'Aéroport mis à jour avec succès !',
      aeroportDeleted: 'Aéroport supprimé avec succès !',
      // New cannot-delete messages
      cannotDeleteAeroport: 'Suppression impossible',
      aeroportInUseByTechniciens: 'Cet aéroport est associé à un ou plusieurs techniciens. Supprimez ou modifiez ces techniciens avant de supprimer l\'aéroport.',
    
      //intervention
      interventionTitle: 'Interventions',
      interventionId: 'ID',
      interventionNumber: 'Numéro ',
      interventionDate: 'Date',
      interventionDuration: 'Durée',
      interventionEndTime: 'Date de fin',
      interventionStartTime: 'Date de début',
      interventionInProgress: 'En cours',
      interventionCompleted: 'Terminé',
      interventionProblem: 'Problème',
      interventionSolution: 'Solution',
      interventionTechnicien: 'Technicien',
      interventionCampagne: 'Entreprise',
      interventionAeroport: 'Aéroport',
      interventionEquipement: 'Équipement',
      interventionProjet: 'Projet',
      interventionZone: 'Zone d\'intervention',
      interventionComptoir: 'Comptoire',
      interventionEnterNumero: 'Entrez le numéro',
      interventionSubtitle: 'La liste de toutes les interventions',
      addIntervention: 'Nouvelle intervention',
      searchIntervention: ' Rechercher une intervention...',
      noInterventions: 'Aucune intervention trouvée',
      interventionName: 'Nom de l\'intervention',
      enterInterventionName: 'Entrez le nom de l\'intervention',
      interventionExists: 'Une intervention avec ce numéro existe déjà !',
      interventionEmptyField: 'Veuillez remplir tous les champs !',
      confirmDeleteIntervention: 'Voulez-vous vraiment supprimer cette intervention ?',
      interventionAdded: 'Intervention ajoutée avec succès !',
      interventionUpdated: 'Intervention mise à jour avec succès !',
      interventionDeleted: 'Intervention supprimée avec succès !',
      interventionDateDebut: 'Entrez la date de début',
      interventionDateFin: 'Entrez la date de fin',
      interventionAddCampagne: 'Entrez la entreprise',
      interventionAddTechnicien: 'Entrez le technicien',
      interventionAddZone: 'Entrez la zone',
      interventionAddComptoir: 'Entrez le comptoir',
      interventionAddProjet: 'Entrez le projet',
      interventionAddEquipement: 'Entrez l\'équipement',
      interventionAddSolution: 'Entrez la solution',
      interventionAddProblem: 'Entrez le problème',
      interventionAddAeroport: 'Entrez l\'aéroport',
      interventionDownloadAllInterventions: 'Télécharger toutes les interventions',
      interventionDownloadCurrentPage: 'Télécharger la page actuelle'
    },

    en: {
      // Common
      id: 'ID',
      name: 'Name',
      actions: 'Actions',
      add: 'Add',
      edit: 'Edit',
      save: 'Save',
      delete: 'Delete',
      confirm: 'Confirm',
      cancel: 'Cancel',
      emptyField: 'The field is empty!',
      ok: 'OK',
      page: 'Page',
      of: 'of',
      quantity: 'Quantity',
      stock: 'stock',

      // Messages
      confirmDeleteGeneric: 'Are you sure you want to delete this item?',
      actionUndone: 'This action cannot be undone.',
      noResults: 'No results found',

      // Success notifications
      successAdd: 'Successfully added!',
      successEdit: 'Successfully updated!',
      successDelete: 'Successfully deleted!',

      // Companies
      companyTitle: 'Company List',
      companySubtitle: 'The list of all companies',
      addCompany: 'New company',
      searchCompany: ' Search a company...',
      noCompanies: 'No companies found',
      companyName: 'Company Name',
      enterCompanyName: 'Enter company name',
      companyExists: 'A company with this name already exists!',
      companyEmptyField: 'The company name cannot be empty!',
      confirmDeleteCompany: 'Are you sure you want to delete this company?',
      companyAdded: 'Company added successfully!',
      companyUpdated: 'Company updated successfully!',
      companyDeleted: 'Company deleted successfully!',

      // Problems
      problemTitle: 'Problems',
      problemSubtitle: 'The list of all problems',
      addProblem: 'New problem',
      searchProblem: '🔍 Search a problem...',
      noProblems: 'No problems found',
      problemName: 'Problem Name',
      enterProblemName: 'Enter problem name',
      problemExists: 'A problem with this name already exists!',
      problemEmptyField: 'The problem name cannot be empty!',
      confirmDeleteProblem: 'Are you sure you want to delete this problem?',
      problemAdded: 'Problem added successfully!',
      problemUpdated: 'Problem updated successfully!',
      problemDeleted: 'Problem deleted successfully!',

      // Solutions
      solutionTitle: 'Solutions',
      solutionSubtitle: 'The list of all solutions',
      addSolution: 'New solution',
      searchSolution: ' Search a solution...',
      noSolutions: 'No solutions found',
      solutionName: 'Solution Name',
      enterSolutionName: 'Enter solution name',
      solutionExists: 'A solution with this name already exists!',
      solutionEmptyField: 'The solution name cannot be empty!',
      confirmDeleteSolution: 'Are you sure you want to delete this solution?',
      solutionAdded: 'Solution added successfully!',
      solutionUpdated: 'Solution updated successfully!',
      solutionDeleted: 'Solution deleted successfully!',
      // Zones
      zoneTitle: 'Zones',
      zoneSubtitle: 'The list of all zones',
      addZone: 'New zone',
      searchZone: '🔍 Search a zone...',
      noZones: 'No zones found',
      zoneName: 'Zone Name',
      enterZoneName: 'Enter zone name',
      zoneExists: 'A zone with this name already exists!',
      zoneEmptyField: 'The zone name cannot be empty!',
      confirmDeleteZone: 'Are you sure you want to delete this zone?',
      zoneAdded: 'Zone added successfully!',
      zoneUpdated: 'Zone updated successfully!',
      zoneDeleted: 'Zone deleted successfully!',
      cannotDelete: 'Deletion not allowed',
      zoneHasCounters: 'This zone contains counters and cannot be deleted.',
      deleteCountersFirst: 'Please delete all counters associated with this zone first.',
      // Counters
      counterTitle: 'Counters',
      counterSubtitle: 'The list of all counters',
      addCounter: 'New counter',
      searchCounter: ' Search a counter...',
      noCounters: 'No counters found',
      counterName: 'Counter Name',
      enterCounterName: 'Enter counter name',
      selectZone: 'Select a zone',
      zone: 'Zone',
      zoneRequired: 'Zone Required',
      counterNeedsZone: 'Please select a zone for this counter.',
      zoneUnavailable: 'Zone unavailable',
      counterExists: 'A counter with this name already exists!',
      counterEmptyField: 'The counter name cannot be empty!',
      confirmDeleteCounter: 'Are you sure you want to delete this counter?',
      counterAdded: 'Counter added successfully!',
      counterUpdated: 'Counter updated successfully!',
      counterDeleted: 'Counter deleted successfully!',
      
      // Equipment
      equipementTitle: 'Equipment',
      equipementSubtitle: 'List of all equipment',
      addEquipement: 'New equipment',
      searchEquipement: ' Search equipment...',
      noEquipements: 'No equipment found',
      nameEquipement: 'Equipment name',
      enterEquipementName: 'Enter equipment name',
      quantite: 'Quantity',
      enterQuantite: 'Enter quantity',
      equipementExists: 'Equipment with this name already exists!',
      equipementEmptyField: 'Fields cannot be empty!',
      confirmDeleteEquipement: 'Are you sure you want to delete this equipment?',
      equipementAdded: 'Equipment added successfully!',
      equipementUpdated: 'Equipment updated successfully!',
      equipementDeleted: 'Equipment deleted successfully!',
  // Login
  loginTitle: 'Login',
  loginUsername: 'Username',
  loginPassword: 'Password',
  loginEnterUsername: 'Enter your username',
  loginEnterPassword: 'Enter your password',
  loginSubmit: 'Sign in',
  loginMissingFields: 'Please fill in all fields',
  loginInvalid: 'Invalid credentials',
      
      // Projects
      projectTitle: 'Projects',
      projectSubtitle: 'Manage your projects and their equipment',
      addProject: 'New project',
      createProject: 'Create project',
      projectName: 'Project name',
      enterProjectName: 'Enter project name',
      selectEquipment: 'Select equipment',
      equipmentQuantity: 'Quantity',
      selectedEquipments: 'Selected equipment',
      projectListTitle: 'Project list',
      noProjects: 'No projects found',
      modifyProject: 'Modify project',
      saveProject: 'Save project',
      deleteProjectConfirm: 'Are you sure you want to delete this project?',
      projectAdded: 'Project added successfully!',
      projectUpdated: 'Project updated successfully!',
      projectDeleted: 'Project deleted successfully!',
      equipments: 'Equipment',
      addEquipment: 'Add equipment',
      equipment: 'Equipment',
      unknownEquipment: 'Unknown equipment',
      editEquipment: 'Edit',
      deleteEquipment: 'Delete',
      chooseEquipment: 'Choose equipment',
      equipmentStock: 'stock',
      removeEquipment: 'X',

      // Technicians
      firstname: 'Firstname',
      enterFirstname: 'Enter firstname',
      lastname: 'Lastname',
      enterLastname: 'Enter lastname',
      pseudoname: 'Pseudoname',
      enterPseudoname: 'Enter pseudoname',
      role: 'Role',
      enterRole: 'Enter role',
      motDePass: 'Password',
      enterMotDePass: 'Enter password',
      aeroport: 'Airport ',
      enterAeroport: 'Choose airport',
      technicienTitle: 'Technicians',
      technicienSubtitle: 'The list of all technicians',
      addTechnicien: 'New technician',
      searchTechnicien: ' Search a technician...',
      noTechniciens: 'No technicians found',
      technicienName: 'Technician Name',
      enterTechnicienName: 'Enter technician name',
      technicienExists: 'A technician with this name already exists!',
      technicienEmptyField: 'Please fill in all fields !',
      confirmDeleteTechnicien: 'Are you sure you want to delete this technician?',
      technicienAdded: 'Technician added successfully!',
      technicienUpdated: 'Technician updated successfully!',
      technicienDeleted: 'Technician deleted successfully!',

      // Aeroports
      aeroportTitle: 'Airports',
      aeroportSubtitle: 'The list of all airports',
      addAeroport: 'New airport',
      searchAeroport: '🔍 Search an airport...',
      noAeroports: 'No airports found',
      aeroportName: 'Airport Name',
      enterAeroportName: 'Enter airport name',
      aeroportExists: 'An airport with this name already exists!',
      aeroportEmptyField: 'The airport name cannot be empty!',
      confirmDeleteAeroport: 'Are you sure you want to delete this airport?',
      aeroportAdded: 'Airport added successfully!',
      aeroportUpdated: 'Airport updated successfully!',
      aeroportDeleted: 'Airport deleted successfully!',
      cannotDeleteAeroport: 'Cannot delete airport',
      aeroportInUseByTechniciens: 'This airport is linked to one or more technicians. Please delete or modify these technicians before deleting the airport.',


      //intervention
      interventionTitle: 'Interventions',
      interventionId: 'ID',
      interventionNumber: 'Number ',
      interventionDate: 'Date',
      interventionDuration: 'Duration',
      interventionEndTime: 'End Time',
      interventionStartTime: 'Start Time',
      interventionInProgress: 'In Progress',
      interventionCompleted: 'Completed',
      interventionProblem: 'Problem',
      interventionSolution: 'Solution',
      interventionTechnicien: 'Technician',
      interventionCampagne: 'Company',
      interventionAeroport: 'Airport',
      interventionEquipement: 'Equipment',
      interventionZone: 'Intervention Zone',
      interventionComptoir: 'Counter',
      interventionProjet: 'Project',
      interventionSubtitle: 'The list of all interventions',
      addIntervention: 'New intervention',
      searchIntervention: '🔍 Search an intervention...',
      noInterventions: 'No interventions found',
      interventionName: 'Intervention Name',
      enterInterventionName: 'Enter intervention name',
      interventionExists: 'An intervention with this number already exists!',
      interventionEmptyField: 'Please fill in all fields!',
      confirmDeleteIntervention: 'Are you sure you want to delete this intervention?',
      interventionAdded: 'Intervention added successfully!',
      interventionUpdated: 'Intervention updated successfully!',
      interventionDeleted: 'Intervention deleted successfully!',
      interventionEnterNumero: 'Entrez le numéro de l\'intervention',
      interventionDateDebut: 'Enter start date',
      interventionDateFin: 'Enter end date',
      interventionAddCampagne: 'Enter company',
      interventionAddTechnicien: 'Enter technician',
      interventionAddZone: 'Enter zone',
      interventionAddComptoir: 'Enter counter',
      interventionAddProjet: 'Enter project',
      interventionAddEquipement: 'Enter equipment',
      interventionAddSolution: 'Enter solution',
      interventionAddProblem: 'Enter problem',
      interventionAddAeroport: 'Enter airport',
      interventionDownloadAllInterventions: 'Download all interventions',
      interventionDownloadCurrentPage: 'Download current page'

    }
  };

  private entityTypes = {
    fr: [
      { value: 'campagny', label: 'Compagnie' },
      { value: 'problem', label: 'Problème' },
      { value: 'solution', label: 'Solution' },
      { value: 'staff', label: 'Personnel' },
      { value: 'zone', label: 'Zone' },
      { value: 'comptoire', label: 'Comptoire' },
      { value: 'technicien', label: 'Technicien' },
      { value: 'project', label: 'Projet' },
      { value: 'equipement', label: 'Équipement' },
      { value: 'intervention', label: 'Intervention' }
    ],
    en: [
      { value: 'campagny', label: 'Company' },
      { value: 'problem', label: 'Problem' },
      { value: 'solution', label: 'Solution' },
      { value: 'staff', label: 'Staff' },
      { value: 'zone', label: 'Zone' },
      { value: 'comptoire', label: 'Counter' },
      { value: 'technicien', label: 'Technician' },
      { value: 'project', label: 'Project' },
      { value: 'equipement', label: 'Equipment' },
      { value: 'intervention', label: 'Intervention' }
    ]
  };

  get lang(): Lang {
    return this.langSubject.value;
  }

  toggleLang() {
    const nextLang: Lang = this.lang === 'fr' ? 'en' : 'fr';
    this.langSubject.next(nextLang);
  }

  setLang(lang: Lang) {
    this.langSubject.next(lang);
  }

  get t() {
    return this.translations[this.lang];
  }

  get entityTypeList() {
    return this.entityTypes[this.lang];
  }
}